### ISSUE TITLE
In staging, the bullets are not homogen

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#274]
![Capture d’écran de 2022-10-18 09-24-35](https://user-images.githubusercontent.com/85115963/196364169-ca47941e-810d-4b29-9f0f-e5d7e628cb1c.png)

One is at +4 and has a hover on it

**Comment by benjaminbrgs** [comment]
It's the correct behavior for me. When more than 2 skills are in the same level, they are grouped together in one round.

**Comment by ThomG317** [comment]
In the section my skills, the "+" is always displayed, is it normal ?

**Comment by ThomG317** [comment]
@benjaminbrgs, @MailyLehoux I've started working on implementing solution 1 regarding our last conversation. However I came across an inconsistence in terms of the usage of bullets.

As you can see on the first screen bellow, bullet labels are used as caption to identifiy a skill, therefore applying a regroup logic is not possible because each skills is uniquely identified by a number.
![Screenshot 2022-11-23 at 09 52 24](https://user-images.githubusercontent.com/62474391/203505327-541a1983-ffcf-4b53-a65a-5345edd88d5e.png)


However when zooming into a category, the bullet labels become the number of skills regrouped at the same location on the graph.
![image](https://user-images.githubusercontent.com/62474391/203505803-72c15728-1578-44bf-ab67-680ce854fa35.png)

As a user I find it quite confusing, the content of bullet is always a number but the meaning behind it changes. It adds another layer of complexity preventing the implementation of a simple solution. I would like to have your thougths on this, to either unify it, or clarify with non-ambigous rules that cover all the cases (implying specific design to distinct each case).
