### ISSUE TITLE
Badge system 

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#81]
The user can have 5 different badges, and starts Bronze 0xp : 
- Bronze (50xp)
- Silver (150xp)
- Gold (250xp)
- Platin (400xp)
- Diamond (infinite)

These ranks have their owns xp bar (higher is the rank, higher the xp to have to climb). 

**The user can gain 10xp/tech added**

**The user can lose 5xp if he/she didn't evaluate a new tech on the app for 7 days. Every 7 days he/she can lose 5xp. An update on a skill may be count as a new tech**

![webp](https://user-images.githubusercontent.com/85115963/121858484-f33fd500-ccf6-11eb-9ba0-6af6e09324d2.png)

The badge can be shown on the profile page, and if we click on it, we can see a general classment, sorted in descending order. A new tab can be added as well

**Comment by hgwood** [comment]
Did you make those? There are really nice

**Comment by MailyLehoux** [comment]
Yes there are nice. But it wasn't me the designer I found it on this website : https://dribbble.com/shots/1470374-Badges-for-Online-Game?list=following 

I'm not sure about the rights for theses badges, so I did some research : 
![04l7sec68zn61](https://user-images.githubusercontent.com/85115963/122183741-d25cb880-ce8b-11eb-910f-e93f0b632cc8.png)

Some icons can represent the badges, and there are free found on the reddit community https://www.reddit.com/r/gameassets/

what do you think of all this?

**Comment by Ked57** [comment]
I was thinking we could do it like this

- Define some objectives for the users for example:
  - A number of skills to input
  - Update their profile at least once a month
  - etc ...
- For each objective, define sub-objectives, for example:
  -  Bronze: 5 skills
  -  Silver: 10 skills
  -  etc ...
- We could then reward users with a badge per objective, so if you entered 10 skills and updated them for 3 months in a row you could have:
  - Silver badge for input
  - Gold badge for recurrency
- Theses badges would all be displayed on the users profile

I think this could be a nice system 😄 

I am a little bit worried that experience points and leaderboard would make the user feel like they have to enter the maximum amount of skills and update them all every week which could feel like farming in video games. This would also probably make our data less precise since some skills are just bound to be at 1 or 2 and never change 😄 

Good stuff nonetheless 👍  We need to organise a call with everyone to talk about it

**Comment by Ked57** [comment]
There's a lot of stuff that still need to be changed in your pull request, let's revert it on main branch and reopen it
